// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _6132016TW : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6132016TW));
        
        string IMigrationMetadata.Id
        {
            get { return "201606130616565_6132016TW"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
